# Generated by Django 5.2.6 on 2025-11-11 17:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_userprofile_avatar_userprofile_is_top_helper_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='helprequest',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
